# Generated by Django 5.1.6 on 2025-03-04 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_count', models.IntegerField(default=0)),
                ('amber_count', models.IntegerField(default=0)),
                ('green_count', models.IntegerField(default=0)),
                ('better_count', models.IntegerField(default=0)),
                ('same_count', models.IntegerField(default=0)),
                ('worse_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_summaries', to='healthcards.healthcard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_summaries', to='healthcards.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='accounts.team')),
            ],
            options={
                'unique_together': {('team', 'health_card', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], max_length=5)),
                ('trend', models.CharField(choices=[('better', 'Getting Better'), ('same', 'Same'), ('worse', 'Getting Worse')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_votes', to='healthcards.healthcard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_votes', to='healthcards.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_votes', to='accounts.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'team', 'health_card', 'session')},
            },
        ),
    ]
