# Generated by Django 5.1.6 on 2025-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsummary',
            name='amber_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teamsummary',
            name='better_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teamsummary',
            name='green_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teamsummary',
            name='red_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teamsummary',
            name='same_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teamsummary',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamsummary',
            name='worse_percentage',
            field=models.FloatField(default=0),
        ),
    ]
