# Generated by Django 5.1.4 on 2025-04-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ENGINEER', 'Engineer'), ('TEAM_LEADER', 'Team Leader'), ('DEPARTMENT_LEADER', 'Department Leader'), ('SENIOR_MANAGER', 'Senior Manager')], default='ENGINEER', max_length=30),
        ),
    ]
