# Generated by Django 5.1.6 on 2025-04-18 17:44

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_members', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ENGINEER', 'Engineer'), ('TEAM_LEADER', 'Team Leader'), ('DEPARTMENT_LEADER', 'Department Leader'), ('SENIOR_MANAGER', 'Senior Manager')], default='ENGINEER', max_length=20),
        ),
    ]
